### ISSUE TITLE
iOS and Android seem to report different times (milliseconds vs. seconds)

### ISSUE THREAD

**Issue by bkoznov** [anandnet/flutter_video_info#10]
In iOS video time is returned in seconds, but in Android is is returned  in milliseconds. I think that on iOS it should be converted to milliseconds as well, because in `flutter_video_info.dart` line 61 and onwards:

```  
// millisecond
  double duration;

  VideoData({
    @required this.path,
    this.title,
    this.author,
    this.mimetype,
    this.date,
    this.location,
    this.framerate,
    this.width,
    this.height,
    this.orientation,
    this.filesize,
    this.duration,
  });
```

**Comment by anandnet** [comment]
@bkoznov this has been fixed in new version. thanks for pointing out .
