### ISSUE TITLE
flutter_video_info is not working in android 33

### ISSUE THREAD

**Issue by Sayedmdkaif** [anandnet/flutter_video_info#22]
G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_video_info-1.2.0\android\src\main\java\com\example\flutter_video_info\FlutterVideoInfoPlugin.java:92: error: unreported exception IOException; must be caught or declared to be thrown
            mediaRetriever.release();
                                  ^
Note: G:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_video_info-1.2.0\android\src\main\java\com\example\flutter_video_info\FlutterVideoInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_video_info:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by nagendarbalajij-devs** [comment]
@anandnet I have made a fix for this issue and raised a PR

**Comment by anandnet** [comment]
@nagendarbalajij-devs many thanks for your pr.
fix already merged in #23 & flutter_video_info v1.3.1 released.
