### ISSUE TITLE
android6.0  get info crash

### ISSUE THREAD

**Issue by yingqiang006** [anandnet/flutter_video_info#3]
[ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-libart.jar)
E/flutter (18164): 	at com.example.flutter_video_info.FlutterVideoInfoPlugin.getVidInfo(FlutterVideoInfoPlugin.java:62)
E/flutter (18164): 	at com.example.flutter_video_info.FlutterVideoInfoPlugin.onMethodCall(FlutterVideoInfoPlugin.java:48)
E/flutter (18164): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (18164): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (18164): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (18164): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (18164): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (18164): 	at android.os.Looper.loop(Looper.java:163)
E/flutter (18164): 	at android.app.ActivityThread.main(ActivityThread.java:5769)
E/flutter (18164): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18164): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/flutter (18164): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
E/flutter (18164): 
F/flutter (18164): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).

**Comment by themadmrj** [comment]
Same error here, any idea how to fix it? Otherwise I'll sadly have to find another package...
