### ISSUE TITLE
Provide video orientation in iOS also

### ISSUE THREAD

**Issue by keval-d** [anandnet/flutter_video_info#9]
I checked plugin iOS code but i did't find code for orientation.

For reference : https://gist.github.com/wdcurry/433dd1db8f315cf6edd9ff8d2ee6f411

**Comment by anandnet** [comment]
@keval-d  thanks for your reference it helped a lot, I have added this in the new version

**Comment by keval-d** [comment]
I wrote this function for find video orientation in iOS.

`jsonObj["orientation"] = String(videoOrientaion(tracks: tracks))

private func videoOrientaion(tracks :[AVAssetTrack]) -> Int {
        if let videoTrack = tracks.first {
            let txf = videoTrack.preferredTransform
            return Int(Double(atan2(txf.b, txf.a) * 180) / Double.pi)
        }
        return 0
    }`

**Comment by keval-d** [comment]
This solved my issue.

`jsonObj["orientation"] = String(videoOrientation(tracks: tracks))`

```
private func videoOrientation(tracks :[AVAssetTrack]) -> Int {
        if let videoTrack = tracks.first {
            let txf = videoTrack.preferredTransform
            return Int(Double(atan2(txf.b, txf.a) * 180) / Double.pi)
        }
        return 0
    }
```
